
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const S={goals:{recruit:1,bv:1500,ibv:300},data:{recruit:[],bv:[],ibv:[]},flags:{reachedRecruit:false,reachedBV:false,reachedIBV:false}};

function init(){
  Object.assign(S.goals,store.get('goals',S.goals));
  Object.assign(S.data,store.get('data',S.data));
  Object.assign(S.flags,store.get('flags',S.flags));
  goalRecruit.value=S.goals.recruit;goalBV.value=S.goals.bv;goalIBV.value=S.goals.ibv;
  saveGoals.onclick=()=>{S.goals.recruit=+goalRecruit.value||0;S.goals.bv=+goalBV.value||0;S.goals.ibv=+goalIBV.value||0;store.set('goals',S.goals);recalc();};
  const t=new Date().toISOString().slice(0,10);
  recDate.value=bvDate.value=ibvDate.value=memDate.value=t;
  document.querySelectorAll('.tabs button').forEach(b=>{b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelector('#tab-'+b.dataset.tab).classList.add('active');};});
  addRecruit.onclick=()=>{const name=recName.value.trim();if(!name)return alert('請輸入姓名');S.data.recruit.push({date:recDate.value,name});store.set('data',S.data);recName.value='';recalc();};
  addBV.onclick=()=>{const name=bvName.value.trim()||'（未填）';const item=bvItem.value.trim()||'-';const qty=+bvQty.value||0;if(qty<=0)return alert('請輸入 BV 數量');S.data.bv.push({date:bvDate.value,name,item,qty});store.set('data',S.data);bvItem.value='';bvQty.value='';recalc(true,'bv');};
  addIBV.onclick=()=>{const name=ibvName.value.trim()||'（未填）';const item=ibvItem.value.trim()||'-';const qty=+ibvQty.value||0;if(qty<=0)return alert('請輸入 IBV 數量');S.data.ibv.push({date:ibvDate.value,name,item,qty});store.set('data',S.data);ibvItem.value='';ibvQty.value='';recalc(true,'ibv');};
  addMem.onclick=()=>{const name=memName.value.trim();const group=memGroup.value.trim();if(!name||!group)return alert('請填姓名與族群');const note=memNote.value.trim();const city=citySel.value;const d=memDate.value;const arr=store.get('memList',[]);let x=arr.find(v=>v.name===name&&v.city===city&&v.group===group);if(!x){x={name,city,group,logs:[]};arr.push(x);}x.logs.push({date:d,note});store.set('memList',arr);const names=new Set(store.get('names',[]));names.add(name);store.set('names',Array.from(names));const groups=new Set(store.get('groups',[]));groups.add(group);store.set('groups',Array.from(groups));memName.value='';memGroup.value='';memNote.value='';render312();};
  clearFields.onclick=()=>{memName.value='';memGroup.value='';memNote.value='';};
  exportCsv.onclick=exportAll; closeModal.onclick=()=>modal.classList.add('hidden'); refreshDatalists(); recalc();
}
function recalc(){renderRecruit();renderAgg('bv',bvTable,bvSumText);renderAgg('ibv',ibvTable,ibvSumText);render312();updateProgress();}
function renderRecruit(){const tb=recTable.querySelector('tbody');tb.innerHTML='';S.data.recruit.forEach((r,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${r.date}</td><td>${r.name}</td><td><button class="ghost" data-del="${i}">刪除</button></td>`;tb.appendChild(tr);});tb.querySelectorAll('button[data-del]').forEach(b=>b.onclick=()=>{const i=+b.dataset.del;S.data.recruit.splice(i,1);store.set('data',S.data);recalc();});recSummary.textContent=`目前累計：${S.data.recruit.length} / ${S.goals.recruit} 人`;}

function renderAgg(key,tableEl,sumEl){const rows=S.data[key];const map=new Map();let sum=0;rows.forEach(r=>{sum+=r.qty;const k=r.name;if(!map.has(k))map.set(k,{name:k,qty:0,count:0,items:[]});const o=map.get(k);o.qty+=r.qty;o.count++;o.items.push(r);});const tb=tableEl.querySelector('tbody');tb.innerHTML='';Array.from(map.values()).forEach((o,idx)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${idx+1}</td><td>${o.name}</td><td>${o.qty}</td><td>${o.count}</td><td><button class="ghost" data-view="${o.name}">查看</button></td><td><button class="ghost" data-del="${o.name}">刪除</button></td>`;tb.appendChild(tr);});tb.querySelectorAll('button[data-view]').forEach(b=>b.onclick=()=>{const n=b.dataset.view;const items=rows.filter(x=>x.name===n).map(x=>`${x.date} | 賣 ${x.item} × ${x.qty}`).join('\n');modalContent.innerHTML=`<pre>【${n}】\n${items}</pre>`;modal.classList.remove('hidden');});tb.querySelectorAll('button[data-del]').forEach(b=>b.onclick=()=>{const n=b.dataset.del;const left=rows.filter(x=>x.name!==n);S.data[key]=left;store.set('data',S.data);recalc();});if(key==='bv'){sumEl.textContent=`目前累計：${sum} / ${S.goals.bv} BV`;bvTargetTitle.textContent=`${S.goals.bv} BV`;}else{sumEl.textContent=`目前累計：${sum} / ${S.goals.ibv} IBV`;ibvTargetTitle.textContent=`${S.goals.ibv} IBV`;}}

function render312(){refreshDatalists();const arr=store.get('memList',[]);const tb=memTable.querySelector('tbody');tb.innerHTML='';arr.forEach((p,i)=>{const latest=p.logs.slice().sort((a,b)=>b.date.localeCompare(a.date))[0]?.date||'-';const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${p.city}</td><td>${p.name}</td><td>${p.group}</td><td>${latest}</td><td>${p.logs.length}</td><td><button class="ghost" data-view="${i}">查看</button></td>`;tb.appendChild(tr);});tb.querySelectorAll('button[data-view]').forEach(b=>b.onclick=()=>{const i=+b.dataset.view;const p=store.get('memList',[])[i];const title=`【${p.name}】(${p.city}｜${p.group})`;const lines=p.logs.sort((a,b)=>a.date.localeCompare(b.date)).map(v=>`${v.date} | ${v.note||'-'}`).join('\n');modalContent.innerHTML=`<pre>${title}\n${lines}</pre>`;modal.classList.remove('hidden');});}
function refreshDatalists(){nameList.innerHTML=(store.get('names',[])).map(n=>`<option value="${n}">`).join('');groupList.innerHTML=(store.get('groups',[])).map(n=>`<option value="${n}">`).join('');}
function pct(v,g){if(g<=0)return 0;return Math.round(v/g*100)}
function updateProgress(){const recCnt=S.data.recruit.length;const bvSum=S.data.bv.reduce((a,b)=>a+b.qty,0);const ibvSum=S.data.ibv.reduce((a,b)=>a+b.qty,0);setPbar(pRecruit,pRecruitText,Math.min(100,pct(recCnt,S.goals.recruit)));setPbar(pBV,pBVText,Math.min(100,pct(bvSum,S.goals.bv)));setPbar(pIBV,pIBVText,Math.min(100,pct(ibvSum,S.goals.ibv)));currentGoalText.textContent=`目前目標：招募 ${S.goals.recruit} 人 / BV ${S.goals.bv} / IBV ${S.goals.ibv}`;}
function setPbar(el,txt,v){el.style.width=v+'%';txt.textContent=v+'%';if(v>=100)el.classList.add('ok');else el.classList.remove('ok');}
function exportAll(){const lines=[];lines.push('類型,日期,姓名,品項/備註,數量');S.data.recruit.forEach(x=>lines.push(`招募,${x.date},${x.name},,`));S.data.bv.forEach(x=>lines.push(`BV,${x.date},${x.name},${x.item},${x.qty}`));S.data.ibv.forEach(x=>lines.push(`IBV,${x.date},${x.name},${x.item},${x.qty}`));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='IFNT_export.csv';a.click();}
window.addEventListener('load',init);
