const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k)??JSON.stringify(d));}catch(e){return d;}},set(k,v){localStorage.setItem(k,JSON.stringify(v));}};
let goals=store.get('ifnt_goals_v2',{recruit:1,bv:1500,ibv:300});
let recruit=store.get('ifnt_recruit_v2',[]);let bv=store.get('ifnt_bv_v2',[]);let ibv=store.get('ifnt_ibv_v2',[]);
let contacts=store.get('ifnt_contacts_v2',{});
const uuid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const norm=s=>(s||'').toString().trim().replace(/\s+/g,'').toLowerCase(); const today=()=>new Date().toISOString().slice(0,10);
['#r_date','#b_date','#i_date','#p_date'].forEach(id=>$(id).value=today());
function renderGoals(){ $('#goalRecruit').value=goals.recruit; $('#goalBV').value=goals.bv; $('#goalIBV').value=goals.ibv;
 $('#goalText').textContent=`招募 ${goals.recruit} / BV ${goals.bv} / IBV ${goals.ibv}`;
 const rc=recruit.length, bsum=bv.reduce((a,c)=>a+(+c.value||0),0), isum=ibv.reduce((a,c)=>a+(+c.value||0),0);
 const rPct=goals.recruit?Math.min(100,Math.round(rc/goals.recruit*100)):0;
 const bPct=goals.bv?Math.min(100,Math.round(bsum/goals.bv*100)):0;
 const iPct=goals.ibv?Math.min(100,Math.round(isum/goals.ibv*100)):0;
 $('#recruitProgress').style.width=rPct+'%'; $('#bvProgress').style.width=bPct+'%'; $('#ibvProgress').style.width=iPct+'%';
 $('#recruitProgressText').textContent=rPct+'%'; $('#bvProgressText').textContent=bPct+'%'; $('#ibvProgressText').textContent=iPct+'%';
 $('#recruitCounter').textContent=`${rc}/${goals.recruit}`; $('#bvCounter').textContent=`${bsum}/${goals.bv}`; $('#ibvCounter').textContent=`${isum}/${goals.ibv}`; }
$('#saveGoal').onclick=()=>{ goals={recruit:parseInt($('#goalRecruit').value||'0',10), bv:parseFloat($('#goalBV').value||'0'), ibv:parseFloat($('#goalIBV').value||'0')}; store.set('ifnt_goals_v2',goals); renderGoals(); $('#goalPanel').classList.add('hidden'); };
$('#toggleGoal').onclick=()=>$('#goalPanel').classList.toggle('hidden');
const showPanel=id=>{ ['panelRecruit','panelBV','panelIBV','panel312'].forEach(pid=>$('#'+pid).classList.add('hidden')); $(id).classList.remove('hidden'); };
$('#tabRecruit').onclick=()=>showPanel('#panelRecruit'); $('#tabBV').onclick=()=>showPanel('#panelBV'); $('#tabIBV').onclick=()=>showPanel('#panelIBV'); $('#tab312').onclick=()=>showPanel('#panel312');
let audioCtx,fireBuffer; async function ensureAudio(){ if(!audioCtx){ audioCtx=new (window.AudioContext||window.webkitAudioContext)(); const res=await fetch('assets/fireworks.wav'); const buf=await res.arrayBuffer(); fireBuffer=await audioCtx.decodeAudioData(buf);} }
async function boom(){ try{ await ensureAudio(); const src=audioCtx.createBufferSource(); src.buffer=fireBuffer; const g=audioCtx.createGain(); g.gain.value=0.95; src.connect(g).connect(audioCtx.destination); src.start(); }catch(e){} confetti(); }
function confetti(){ const c=$('#fx'),ctx=c.getContext('2d'); c.width=innerWidth; c.height=innerHeight;
 const parts=Array.from({length:120},()=>({x:c.width/2,y:c.height*0.3,vx:(Math.random()-0.5)*6,vy:Math.random()*-5-2,ax:0,ay:0.15,r:2+Math.random()*3,h:160+Math.random()*60,t:0}));
 let t=0; const raf=()=>{ t++; ctx.clearRect(0,0,c.width,c.height); parts.forEach(p=>{ p.vx+=p.ax; p.vy+=p.ay; p.x+=p.vx; p.y+=p.vy; p.t+=1; ctx.fillStyle=`hsl(${p.h},90%,60%)`; ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2); ctx.fill();}); if(t<160) requestAnimationFrame(raf); else ctx.clearRect(0,0,c.width,c.height); }; requestAnimationFrame(raf); }
function renderRecruit(){ const tb=$('#r_tbody'); tb.innerHTML=''; recruit.forEach((r,i)=>{ const tr=document.createElement('tr'); tr.className='rowcard'; tr.innerHTML=`<td>${i+1}</td><td>${r.date}</td><td>${r.name||''}</td><td><button class="btn small danger" data-id="${r.id}">刪除</button></td>`; tb.appendChild(tr); }); $('#recruitTotal').textContent=recruit.length; store.set('ifnt_recruit_v2',recruit); renderGoals(); }
$('#addRecruit').onclick=async()=>{ recruit.push({id:uuid(),date:$('#r_date').value||today(),name:$('#r_name').value.trim()}); renderRecruit(); if(recruit.length>=(goals.recruit||0)&&goals.recruit>0) await boom(); };
$('#r_tbody').addEventListener('click',e=>{ if(e.target.matches('button[data-id]')){ const id=e.target.getAttribute('data-id'); recruit=recruit.filter(x=>x.id!==id); renderRecruit(); } });
function aggregateByName(list){ const m=new Map(); list.forEach(x=>{ const key=norm(x.name); if(!m.has(key)) m.set(key,{name:x.name||'(未填)',total:0,count:0,logs:[]}); const o=m.get(key); o.total += (+x.value||0); o.count += 1; o.logs.push(x); }); return Array.from(m.values()).sort((a,b)=>b.total-a.total); }
function renderBV(){ const agg=aggregateByName(bv); const tb=$('#b_tbody'); tb.innerHTML=''; agg.forEach((p,i)=>{ const tr=document.createElement('tr'); tr.className='rowcard'; tr.innerHTML=`<td>${i+1}</td><td>${p.name}</td><td>${p.total}</td><td>${p.count}</td><td><button class="btn small ghost" data-view="${norm(p.name)}">查看</button></td><td><button class="btn small danger" data-del="${norm(p.name)}">刪除</button></td>`; tb.appendChild(tr); }); const total=bv.reduce((a,c)=>a+(+c.value||0),0); $('#bvTotal').textContent=total; store.set('ifnt_bv_v2',bv); renderGoals(); }
$('#addBV').onclick=async()=>{ const rec={id:uuid(),date:$('#b_date').value||today(),name:$('#b_name').value.trim(),item:$('#b_item').value.trim(),value:parseFloat($('#b_value').value||'0')}; if(!isFinite(rec.value))return; bv.push(rec); renderBV(); const sum=bv.reduce((a,c)=>a+(+c.value||0),0); if(sum>=(goals.bv||0)&&goals.bv>0) await boom(); };
$('#b_tbody').addEventListener('click',e=>{ if(e.target.matches('button[data-view]')){ const key=e.target.getAttribute('data-view'); const logs=bv.filter(x=>norm(x.name)===key).sort((a,b)=>a.date>b.date?-1:1); $('#modalTitle').textContent=`【${logs[0]?.name||'(未填)'}】BV 明細`; $('#modalContent').textContent=logs.map(x=>`${x.date}｜${x.item}  ${x.value}`).join('\\n'); $('#modalBackdrop').style.display='flex'; } else if(e.target.matches('button[data-del]')){ const key=e.target.getAttribute('data-del'); bv=bv.filter(x=>norm(x.name)!==key); renderBV(); } });
function renderIBV(){ const agg=aggregateByName(ibv); const tb=$('#i_tbody'); tb.innerHTML=''; agg.forEach((p,i)=>{ const tr=document.createElement('tr'); tr.className='rowcard'; tr.innerHTML=`<td>${i+1}</td><td>${p.name}</td><td>${p.total}</td><td>${p.count}</td><td><button class="btn small ghost" data-view="${norm(p.name)}">查看</button></td><td><button class="btn small danger" data-del="${norm(p.name)}">刪除</button></td>`; tb.appendChild(tr); }); const total=ibv.reduce((a,c)=>a+(+c.value||0),0); $('#ibvTotal').textContent=total; store.set('ifnt_ibv_v2',ibv); renderGoals(); }
$('#addIBV').onclick=async()=>{ const rec={id:uuid(),date:$('#i_date').value||today(),name:$('#i_name').value.trim(),item:$('#i_item').value.trim(),value:parseFloat($('#i_value').value||'0')}; if(!isFinite(rec.value))return; ibv.push(rec); renderIBV(); const sum=ibv.reduce((a,c)=>a+(+c.value||0),0); if(sum>=(goals.ibv||0)&&goals.ibv>0) await boom(); };
$('#i_tbody').addEventListener('click',e=>{ if(e.target.matches('button[data-view]')){ const key=e.target.getAttribute('data-view'); const logs=ibv.filter(x=>norm(x.name)===key).sort((a,b)=>a.date>b.date?-1:1); $('#modalTitle').textContent=`【${logs[0]?.name||'(未填)'}】IBV 明細`; $('#modalContent').textContent=logs.map(x=>`${x.date}｜${x.item}  ${x.value}`).join('\\n'); $('#modalBackdrop').style.display='flex'; } else if(e.target.matches('button[data-del]')){ const key=e.target.getAttribute('data-del'); ibv=ibv.filter(x=>norm(x.name)!==key); renderIBV(); } });
const contactKey=(city,name)=> norm(city)+'|'+norm(name);
function rebuildNameOptions(){ const dl=$('#nameOptions'); dl.innerHTML=''; Object.values(contacts).sort((a,b)=>a.name>b.name?1:-1).forEach(c=>{ const o=document.createElement('option'); o.value=c.name; dl.appendChild(o); }); }
function renderPeople(){ const tb=$('#p_tbody'); tb.innerHTML=''; const list=Object.values(contacts).sort((a,b)=>(a.city+a.name>b.city+b.name?1:-1)); list.forEach((p,idx)=>{ const tr=document.createElement('tr'); tr.className='rowcard'; const latest=(p.logs||[]).slice().sort((a,b)=>a.date>b.date?-1:1)[0]?.date||''; tr.innerHTML=`<td>${idx+1}</td><td>${p.city}</td><td>${p.name}</td><td>${p.group||''}</td><td>${latest}</td><td>${(p.logs||[]).length}</td><td><button class="btn small ghost" data-view="${contactKey(p.city,p.name)}">查看</button></td>`; tb.appendChild(tr); }); store.set('ifnt_contacts_v2',contacts); rebuildNameOptions(); }
$('#add312').onclick=()=>{ const city=$('#p_city').value, name=$('#p_name').value.trim(); if(!name)return; const k=contactKey(city,name); const group=$('#p_group').value.trim(); const date=$('#p_date').value||today(); const note=$('#p_note').value.trim(); if(!contacts[k]) contacts[k]={city,name,group,logs:[]}; if(group) contacts[k].group=group; contacts[k].logs.push({date,note}); renderPeople(); $('#p_name').value=''; $('#p_group').value=''; $('#p_note').value=''; };
$('#clear312Fields').onclick=()=>{ $('#p_name').value=''; $('#p_group').value=''; $('#p_note').value=''; };
$('#p_tbody').addEventListener('click',e=>{ if(e.target.matches('button[data-view]')){ const key=e.target.getAttribute('data-view'); const c=contacts[key]; if(!c)return; const lines=[`【${c.name}】(${c.city}｜${c.group||''})`].concat((c.logs||[]).slice().sort((a,b)=>a.date>b.date?-1:1).map(x=>`${x.date} ｜ ${x.note||''}`)); $('#modalTitle').textContent='查看資料'; $('#modalContent').textContent=lines.join('\\n'); $('#modalBackdrop').style.display='flex'; } });
$('#modalClose').onclick=()=> $('#modalBackdrop').style.display='none';
$('#exportCsv').onclick=()=>{ const rows=[['type','date','name','item/note','value/city']]; recruit.forEach(x=>rows.push(['recruit',x.date,x.name,'',''])); bv.forEach(x=>rows.push(['bv',x.date,x.name,x.item,x.value])); ibv.forEach(x=>rows.push(['ibv',x.date,x.name,x.item,x.value])); Object.values(contacts).forEach(c=>(c.logs||[]).forEach(l=>rows.push(['312',l.date,c.name,l.note,c.city]))); const csv=rows.map(r=>r.map(v=>`"${(v??'').toString().replace(/"/g,'""')}"`).join(',')).join('\\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`IFNT_export_${new Date().toISOString().slice(0,10)}.csv`; a.click(); };
renderGoals(); renderRecruit(); renderBV(); renderIBV(); renderPeople(); showPanel('#panelBV');